process faults {5: ({4, 2}, 306277623)}
network faults {2: [{0, 1}, {2}, {5, 3}, {4, 6}]}
{9: ("C4A6413B7CBD26B98E1024A354B9FE85344AA47BFB0ACB55A366FB5E15427AA6", {4, 2, 3, 1, 5, 6, 0}), 5: ("52AC58B306AA2DAFEC51BD97138F6B1A5751664CC49631E65AE0E479F983A8EA", {2, 3, 6, 5, 1, 0, 4}), 8: ("73424F8FDF6D348390887A545A2FA5E428BC27FA321E6C1202CB630214ACE8B8", {6, 2, 0, 5, 3, 4, 1}), 6: ("17C3C0654FB223E57636FD1E5D107A308F2329C7D3F7523E782F43B7AF600D48", {2, 3, 6, 0, 1, 4, 5}), 7: ("361B78129ED85E13FCF712940A1FF35876446C0D7CD57BE0FF1790EE46AE8EC2", {6, 3, 1, 5, 2, 4, 0}), 10: ("BCF99B7620C8EE5F6CA7393D1F74B4191E52028207938917DB6A3BE99DFAAC29", {5, 6, 1, 2, 0, 3, 4})}
7
reason: all committed
done!
