process faults {3: ({4, 0}, 49161067)}
network faults {}
{8: ("6D3D3989D3A73FAEE70BB4578EACCA8E0BB50D80BBBA3336941CABBC7A145F57", {5, 1, 2, 4, 3, 0, 6}), 7: ("46DDEA38086C2283D631CD7F6180ADE3FDD4F958BF9C3A539EA02524EFD0C6FA", {2, 0, 5, 4, 6, 1, 3}), 5: ("197A98689FFC8661492F1B894E1FE6D1D116D451CB1816DF189550D5998E305C", {5, 2, 6, 4, 0, 1, 3}), 6: ("7B89A387109E5187BE833EDE0588858079FA620A858717DF24910E43DA597F7D", {1, 6, 2, 3, 4, 0, 5}), 9: ("37EBF6B7A618E8449B368096B564DCC9902AA907C374A88C50DBDEAAD6A3495E", {5, 1, 3, 2, 0, 4, 6}), 10: ("002CC5825BE1556013C66EC080B88307CB41881DBF1137CC59F78915FDF4EC18", {5, 6, 2, 1, 0, 3, 4})}
7
reason: all committed
done!
