process faults {2: ({2, 4, 1}, 3750906746)}
network faults {3: [{0, 6}, {1}, {3, 2}, {4}, {5}]}
{8: ("952A62AFB7D028D561398B700CEE02F37F11B7DEC883A5D768DB909564E23FF9", {0, 3, 1, 6, 4, 5, 2}), 6: ("C934B3EE7A71EE8DB12C5A6F9C734A9CEA0EB5F5DABF320024DF146D216F2499", {6, 4, 5, 2, 1, 3, 0}), 5: ("9CAD32C468DA8F1F02D83FACDD1B46090C1B00340DF6823606CDAEEB560C200A", {3, 4, 6, 2, 0, 5, 1}), 7: ("482AE7565331ECDFB98C05AFAA697E15805EAE3316110C3C26129CB5A968EED4", {5, 1, 4, 6, 0, 3, 2}), 10: ("9946066A1B6BE7F6693EB5AFE2AB63D8D745412E3A88099A45597FAA86B33674", {4, 5, 3, 1, 6, 0, 2}), 9: ("12EA1A44D060B4A15A2A85865F1E51C64CA44987A750AA1773BC8EED2D0D4B1A", {6, 1, 2, 0, 4, 5, 3})}
7
reason: all committed
done!
