process faults {5: ({4, 1, 0}, 1058860936)}
network faults {7: [{5, 1, 0}, {2}, {3, 4, 6}]}
{10: ("44DDBC482858F73C901A69354A0390939120A02C62BF1A8EC4B26C609117F5E4", {6, 1, 5, 3, 0, 2, 4}), 9: ("D2650A64BD003D8C0BE9B4661F720AC9912B3F9F0F39FBEA9F520FB968FC04CD", {5, 1, 4, 3, 0, 2, 6}), 8: ("DB8665DE1C5EC7FE5279BC93ED3508DC3F2A2174714F3C52F75B17A18EDF9DB0", {1, 5, 2, 3, 4, 0, 6}), 5: ("A93CA2CF506A7584D5F0C0C098DBD253CF62DA937C4A61E3AA495BA659301A90", {6, 0, 4, 2, 5, 3, 1}), 7: ("83117BE1985A14820DC4C970F1C48D43C303A5AFA4AC91AAE67957C017F5C097", {0, 1, 5, 2, 6, 3, 4}), 6: ("8F5F049A08DBBBAA8FC01CF4CF52A3717C00EE19A0DD8B89CE0DF2A9E11B65A8", {5, 6, 4, 3, 1, 0, 2})}
7
reason: all committed
done!
