process faults {4: ({5, 6}, 3323912711)}
network faults {7: [{6, 0, 2}, {1, 3}, {4}, {5}]}
{6: ("E759547A625A522B8EDCA7A0DDF789468D36BC865E00E6898E133D96B64C0646", {2, 0, 3, 4, 1, 5, 6}), 5: ("52FE164A95229D5C988A06A8BD6536E2487B73BBCD4F11EC966C30374FEEBD89", {5, 1, 6, 0, 3, 4, 2}), 8: ("99B24E8B856661BAE71231ED275149C05AB1ABBFC5F05F289ACFFD7C8700055C", {2, 0, 4, 6, 3, 1, 5}), 9: ("5E06D11CB4486DFAD8184A2A011802C41835AF1961395708CFA66AA4D98DE881", {5, 1, 3, 4, 0, 2, 6}), 10: ("2D57B6939C4C97A55AE215CC146A7315B91411E716C3968B38BEF03E9C832A41", {5, 2, 1, 3, 4, 6, 0}), 7: ("2286B2742B5E75525FEF125F5492C7455AC62B42A7F35525A42B6AFB016F7B00", {6, 2, 4, 5, 0, 1, 3})}
7
reason: all committed
done!
