process faults {2: ({4}, 424453152)}
network faults {5: [{6, 0}, {1}, {3, 2, 5}, {4}]}
{5: ("F3EBF931C9329B1B251B77C557C807CDFF595F8D5CE3A0611AB148980545933A", {0, 1, 2, 5, 4, 3, 6}), 8: ("415C356BA4498D58DE004072A15C8269BC75B4F86CE253DFDCB5E77EB9AF6157", {5, 0, 3, 1, 4, 2, 6}), 7: ("969A88A2F6D65FAB43E9C84BD3FDC7778007995758CB6FBC78BE6B91E919E111", {2, 3, 0, 1, 5, 6, 4}), 9: ("40C02AB2A90FA426084B1BCCB4C9866E78BB4B54FBCDAAE4C80745F6DEABF843", {2, 5, 3, 6, 4, 0, 1}), 10: ("FAD5D026CA69F728E674CEDFE5F5360B6481C9ECE5038B75600F8B77EFA75048", {3, 6, 0, 1, 5, 4, 2}), 6: ("FCB4CD11BAEC82814F64B2174B47CDA892943B89013E3D193C007AFDF3B10F49", {6, 4, 1, 0, 3, 5, 2})}
7
reason: all committed
done!
