process faults {4: ({4, 1}, 1245794732)}
network faults {6: [{0}, {5, 2, 1}, {3, 4}, {6}]}
{8: ("3D911AC183934EA7CD41BB2D5551E49A9B23781D230F8F3C48197BD966676F7D", {0, 4, 1, 2, 3, 6, 5}), 9: ("392FD1CD1C72E4CD7E35093AB0C080D9C631C81F9927ACCB89EAF68AA50BB75C", {2, 6, 0, 1, 4, 5, 3}), 10: ("E5C6C4C15607349DC9ACA1E976BB92836617BDF45087704C5EBD4E47C36F7B04", {0, 6, 1, 5, 2, 3, 4}), 5: ("195A827974D3771401B81CB66638B25E5D28BF17D360EEB8FAE9B6E5018D5EC0", {5, 1, 3, 2, 4, 6, 0}), 6: ("F0FA407D597950C6707655438E1E8FBFFA7893A0CF25B13ECF7DD427A6FDE014", {1, 3, 6, 2, 4, 0, 5}), 7: ("FB6224C75CD2D2AD8F6B9CCE543EAA06634B7CD0FD89E132A0A8884A6E13E467", {2, 6, 0, 4, 5, 3, 1})}
7
reason: all committed
done!
