process faults {6: ({4}, 3313577891)}
network faults {3: [{4, 0, 1}, {2}, {3, 6}, {5}]}
{6: ("099DF00351421D6F83E042E3CB59ADBEFF4418E1DC950E6C636A2E0BC6FDC381", {1, 3, 5, 0, 2, 6, 4}), 7: ("02936769DA1716A7217682F87EE8AF9B6A9F208A9BC7EF036E1DCD96C9CB04F6", {0, 1, 3, 6, 2, 4, 5}), 5: ("470CF67C89EBB5C60A2F6A3F62C056FFC713B950EED6E6C9E7C55C73914290CA", {6, 0, 4, 2, 5, 1, 3}), 8: ("95B535CAE86341DFE0680888FD105314D43A5C07AA99B47C099C24FB640A6978", {0, 5, 6, 4, 1, 2, 3}), 9: ("9422E2647862BAA89C695638DA810837E814866C1CA3895DF21541D103306D55", {2, 5, 6, 1, 0, 4, 3}), 10: ("255A8971EBF51A0A93BF22548061B6D94B7F202278B15C9DF6DD173B952C86F4", {0, 1, 2, 5, 4, 6, 3})}
7
reason: all committed
done!
