process faults {5: ({0, 1, 2}, 111678959)}
network faults {7: [{3, 6, 0}, {4, 2, 5, 1}], 2: [{2, 0, 3, 5}, {1}, {4}, {6}]}
{9: ("7FC0AC554BE3F8FFAD5B56701921D7408950D2DF51457EE6DD72F00B1FD6E9FF", {6, 1, 4, 5, 2, 3, 0}), 8: ("1E585497E2E970D3757409E3FD982FEB17B75509FB4F166F9A3C5A35491083D6", {2, 1, 5, 4, 3, 6, 0}), 7: ("E78F3DF0B83B581FCA31769C2E34BED2902C5A87E72A4422379F8149C5346E1B", {6, 5, 4, 3, 0, 1, 2}), 10: ("274E4108EE2E033135F25DB8E272DA738AA81E0C3634F91E76C26B3A56C56CA8", {3, 2, 5, 6, 1, 0, 4}), 5: ("78E010B9A8FA2232C13FD249A351CDF72D92345A90A2F7949C838D55E4672063", {6, 2, 4, 1, 3, 5, 0}), 6: ("FF63DC9FB25766DDA0579C5232CBA1D693084782C4CC4B770EE10002E591546B", {1, 2, 0, 4, 6, 3, 5})}
7
reason: all committed
done!
